name: GitHub Actions
on:
  push:
    branches:
      - dev
      - feature/github-action
  pull_request:
    branches:
      - main
jobs:
  test_job:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.13.0]
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_DATABASE: test
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test --detectOpenHandles


